name: either
description: Error handler library. Support functional type Either.
version: 0.0.1
author: Nikita Avdosev <avdosev1@yandex.ru>
homepage: https://github.com/avdosev
repository: https://github.com/avdosev/either_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.3
